arv/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^wizards/', include('wizards.urls')),
    url(r'^judges/', include('judges.urls')),
    url(r'^manage_images/', include('manage_images.urls')),
    url(r'^manage_tasks/', include('manage_tasks.urls')),
    url(r'^manage_users/', include('manage_users.urls')),
    url(r'^cue/', include('cue.urls', namespace='cue')),

]

# serve files if we are in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'core'
urlpatterns = [
    # url for login page
    url(r'^(?:accounts/login/)?$', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),

    # user is redirected here when he/she has successfuly logged in i.e "accounts/profile/"
    # then views.role_login will take it from there i.e. handling user types and the like
    url(r'^accounts/profile/$', views.role_login, name='role_login'),

    # url for logout request
    url(r'^accounts/logout/$', views.logout_user, name='logout'),

    # url to edit user's own profile
    url(r'^accounts/self_profile/$', views.self_profile, name="self_profile"),

    # url to confirm email and activate new user
    url(r'^accounts/confirm/activate/(?P<user_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.confirm_and_activate, name="confirm_and_activate"),

    url(r'^dashboard/$', views.admin_dashboard, name="admin_dashboard"),

    # url to display  user detail
    url(r'^user_profile/(?P<user_id>\d+)/$', views.user_profile, name="user_profile"),
]

manage_users/urls.py
from django.conf.urls import url

from . import views

app_name = 'manage_users'
urlpatterns = [
    # urls that are associated with managing users
    url(r'^view_users/$', views.view_users, name="view_users"),
    url(r'^register_user/$', views.register_user, name='register_user'),

    # deprecated view url
    # url(r'^edit_user/(?P<user_id>\d+)/$', views.edit_user, name="edit_user"),

    url(r'^get_filtered_users/$', views.get_filtered_users, name="get_filtered_users"),

    url(r'^activate_deactivate_user/$', views.activate_deactivate_user, name="activate_deactivate_user"),
]

manage_users/models.py
from django.db import models

# Create your models here.

manage_users/views.py
import pytz
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group, User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from core.forms import ProfileForm, UserForm
from core.tasks import account_created
from core.tokens import account_activation_token
from core.utils import is_admin, edit_user_logic, get_paginated_items, get_pages, ajax_required, \
    get_status


##############################################################################
# Views Related to Managing Users                                            #
##############################################################################


@user_passes_test(is_admin)
def view_users(request):
    """
    A view to show users and profile info
    """

    users_list = get_user_model().objects.exclude(is_superuser=True)

    users = get_paginated_items(request, users_list)
    pages = get_pages(users)

    # context variable for template
    context = {
        "users": users,
        "pages": pages,
    }

    return render(request, "manage_users/view_users.html", context)


@ajax_required
@user_passes_test(is_admin)
def get_filtered_users(request):
    """
    Return a table of users filtered by submitted criteria
    """

    # get the user attribute to be filtered
    attribute = request.GET.get("attribute")
    # get the search term
    search_term = request.GET.get("search_term").strip()

    if len(search_term) == 0:
        # we don't need filtering criteria
        kwargs = {}
    # if attribute is user attribute
    elif hasattr(request.user, attribute):
        # construct keyword args for field look up
        kwargs = {
            "{0}__{1}".format(attribute, "icontains"): search_term,
        }
    # if attribute is profilte attribute
    elif hasattr(request.user.profile, attribute):
        # construct keyword args for field look up
        kwargs = {
            "{0}__{1}__{2}".format("profile", attribute, "icontains"): search_term,
        }
    else:  # if attribute is user role
        # construct keyword args for field look up
        kwargs = {
            "{0}__{1}__{2}".format("groups", "name", "icontains"): search_term,
        }

    # get the account state to be filtered
    account_state = request.GET.get("account_state")
    if account_state == 'active':
        kwargs['is_active'] = True
    elif account_state == 'inactive':
        kwargs['is_active'] = False

    # get the account type to be filtered
    account_type = request.GET.get("account_type")
    if account_type == 'wizards' or account_type == 'judges':
        kwargs['groups__name'] = account_type

    # get users based on kwargs
    users_list = get_user_model().objects.filter(**kwargs).exclude(is_superuser=True)

    users = get_paginated_items(request, users_list)
    pages = get_pages(users)

    # context variable for template
    context = {
        "users": users,
        "pages": pages,
    }

    return render(request, "manage_users/ajax_responses/filtered_users_table.html", context)


@ajax_required
@user_passes_test(is_admin)
def deactivate_user(request):
    """
    A view to deactivate a user
    """

    user_id = int(request.POST['item_id'])
    user = get_object_or_404(get_user_model(), id=user_id)
    user.is_active = False
    user.save()

    return HttpResponse("Deactivated Successfully")


@ajax_required
@user_passes_test(is_admin)
def activate_deactivate_user(request):
    """
    A view to activate or deactivate a user
    """

    user_id = int(request.POST['user_id'])
    user = get_object_or_404(get_user_model(), id=user_id)

    # activate or deactivate based on request
    if request.POST.get("is_active") == "true":
        user.is_active = False
    else:
        user.is_active = True

    user.save()

    return HttpResponse("Processed Successfully")


@user_passes_test(is_admin)
def register_user(request):
    """
    A view to register new user
    """

    # if form is submitted
    if request.method == "POST":
        # populate both forms from submitted data
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)

        # create new user from form and send an email to the new user if successful
        is_registered = create_user_from_form(request, user_form, profile_form)

        # save the success info if the creating process was successful
        request.session['registered'] = is_registered
        # save the failure info if the creating process was unsuccessful
        request.session['not_registered'] = not is_registered
        # save the errors that could arise from form submission
        request.session['user_form_errors'] = user_form.errors
        request.session['profile_form_errors'] = profile_form.errors

        # redirect to itself
        return redirect(request.path)
    else:  # if request method is GET
        # create new forms
        user_form = UserForm()
        profile_form = ProfileForm()

    # check if there was successful registration of user and invalidate it
    success = get_status(request, "registered", False)
    # check if there was unsuccessful registration of user and invalidate it
    failure = get_status(request, "not_registered", False)
    # get errors if there are any and invalidate them
    user_form_errors = get_status(request, "user_form_errors", {})
    profile_form_errors = get_status(request, "profile_form_errors", {})

    # context variables for template
    context = {
        "user_form": user_form,
        "profile_form": profile_form,
        "timezones": pytz.common_timezones,
        "success": success,
        "failure": failure,
        "user_form_errors": user_form_errors,
        "profile_form_errors": profile_form_errors,
    }

    return render(request, "manage_users/register_user.html", context)


# N.B This method is deprecated
@user_passes_test(is_admin)
def edit_user(request, user_id):
    """
    A view to edit a specific user and profile

    Args:
        request: the http request
        user_id: the current user to be edited

    Returns:
        An http redirect to itself if editing user failed or
        an html that illustrates the change made by editing the user
    """

    # get the user to be edited
    user = get_object_or_404(get_user_model(), id=int(user_id))

    # process logic for editing user and profile
    response = edit_user_logic(request, user)

    # if the response is http redirect, redirect
    # else the response is context variables for template
    if isinstance(response, HttpResponseRedirect):
        return response
    else:
        return render(request, "manage_users/edit_user.html", response)


def create_user_from_form(request, user_form, profile_form):
    """
    A logic to create a new user from form data and send an email to the new user
    to activate his/her account if successful

    Args:
        request: the http request
        user_form: user data populated UserForm instance
        profile_form: user data or default data populated ProfileForm instance

    Returns:
        A boolean indicating if the creation of the user is successful or not
    """

    # if forms are valid, update user with its profile
    if user_form.is_valid() and profile_form.is_valid():
        # create user from form
        new_user = user_form.save(commit=False)
        user_password = User.objects.make_random_password()
        new_user.set_password(user_password)
        new_user.is_active = False
        new_user.save()

        # create profile from form and associate the user with it
        new_profile = profile_form.save(commit=False)
        new_profile.user = new_user
        new_profile.save()

        # assign user to appropriate group
        new_user.groups.clear()
        group = Group.objects.get(name=user_form.cleaned_data['role'])
        group.user_set.add(new_user)

        # create an activation link for the user
        # user_id_b64 = urlsafe_base64_encode(force_bytes(new_user.pk))
        token = account_activation_token.make_token(new_user)
        relative_activation_url = reverse("core:confirm_and_activate", args=[str(new_user.id), token])
        activation_url = request.build_absolute_uri(relative_activation_url)

        # send an email to the new user to activate his/her account
        account_created.delay(new_user.email, new_user.username, user_password,
                              user_form.cleaned_data['role'], activation_url)

        return True

    # if one of the forms is invalid
    return False

manage_users/templates/manage_users/edit_user.html
{% extends "judges/extends/base.html" %}

{% block title %} ARV | Edit User {% endblock %}

{% block heading %} Edit user {% endblock %}

{% block main_content %}
    <section class="content-header">
        <h1 class="text-bold underlined-heading">
            Edit User Profile
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url "core:self_profile" %}">
                Timezone: {{ user.profile.timezone }}&nbsp; <i class="fa fa-edit"></i>
            </a></li>
        </ol>
    </section>

    <!-- section content-header used for symmetry pupose only -->
    <section class="content-header">
        <div class="row">
            <div class="col-md-12">
                {% if user_form_errors %}
                    {% for field, errors in user_form_errors %}
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4>
                                <i class="icon fa fa-warning"></i>
                                Alert!
                            </h4>
                            {{ errors.0|escape }} !
                        </div>
                    {% endfor %}
                {% elif profile_form_errors %}
                    {% for field, errors in profile_form_errors %}
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4>
                                <i class="icon fa fa-warning"></i>
                                Alert!
                            </h4>
                            {{ errors.0|escape }} !
                        </div>
                    {% endfor %}
                {% else %}
                    {% if success %}
                        <div class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4>
                                <i class="icon fa fa-check"></i>
                                Alert!
                            </h4>
                            User is successfully updated.
                        </div>
                    {% endif %}
                    {% if failure %}
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4>
                                <i class="icon fa fa-warning"></i>
                                Alert!
                            </h4>
                            Error while updating user. Please, try again!
                        </div>
                    {% endif %}
                {% endif %}
                <form class="form-horizontal" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="username" class="col-sm-2 control-label">User Name</label>
                        <div class="col-sm-8">
                            <input type='text' name='username' class='form-control'
                                   id="username" value="{{ user_form.username.value }}" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="role" class="col-sm-2 control-label"> User Type</label>
                        <div class="col-sm-8">
                            <label class="radio-inline">
                                <input name="role" id="optionsRadios3" value="wizards"
                                       {% ifequal group "Wizards" %}checked="true"{% endifequal %} type="radio">Wizard
                            </label>
                            <label class="radio-inline">&nbsp;
                                <input name="role" id="optionsRadios2" value="judges"
                                       {% ifequal group "Judges" %}checked="true"{% endifequal %} type="radio">Judge
                            </label>
                            <label class="radio-inline">
                                <input name="role" id="optionsRadios1" value="admins"
                                       {% ifequal group "Admins" %}checked="true"{% endifequal %} type="radio">Admin
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="first_name" class="col-sm-2 control-label">First Name</label>
                        <div class="col-sm-8">
                            <input type="text" name="first_name" id="first_name" class="form-control"
                                   value="{{ user_form.first_name.value }}" placeholder="First Name"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="last_name" class="col-sm-2 control-label">Last Name</label>
                        <div class="col-sm-8">
                            <input type="text" name="last_name" id="last_name" class="form-control"
                                   value="{{ user_form.last_name.value }}" placeholder="Enter Last Name"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-8">
                            <input type="email" name="email" class="form-control" id="inputEmail3"
                                   value="{{ user_form.email.value }}" placeholder="Email"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="contact_no" class="col-sm-2 control-label"> Phone Number</label>
                        <div class="col-sm-8">
                            <input type="text" name="contact_no" id="contact_no" class="form-control"
                                   value="{{ profile_form.contact_no.value }}" placeholder="Phone Number"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="timezone" class="col-sm-2 control-label">Time Zone</label>
                        <div class="col-sm-8">
                            <select class="form-control" name="timezone" id="timezone">
                                {% for tz in timezones %}
                                    <option value="{{ tz }}"
                                            {% if tz == user.profile.timezone %}selected{% endif %}>
                                        {{ tz }}
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="change_password" class="col-sm-2 control-label">Change Password</label>

                        <div class="col-sm-8">
                            <input type="password" name="change_password" class="form-control"
                                   id="change_password" value=""/>
                        </div>
                        <!--<label>
                            <input id="methods" type="checkbox"/>
                                Show password
                        </label>-->
                    </div>
                    <div class="form-group">
                        <label for="picture" class="col-sm-2 control-label">Change Profile Picture</label>
                        <div class="col-sm-8">
                            <input type="file" name="pictrue" id="picture" class="form-control" accept="image/*"/>
                        </div>
                    </div>


                    <div class="form-group">
                        <!--<button type="submit" class="btn btn-info "> Save </button>
                      <button type="submit" class="btn btn-default"> Cancel </button>-->
                        <div class="col-sm-offset-2 col-sm-8">
                            <button type="submit" class="btn btn-primary" name="btn-save">
                                <i class="fa fa-upload"></i> &nbsp;Update User Profile
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

manage_users/templates/manage_users/view_users.html
{% extends "judges/extends/base.html" %}

{% block title %} ARV | View Users {% endblock %}

{% block main_content %}
    <section class="content-header">
        <h1 class="text-bold underlined-heading">
            All Users
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url "core:self_profile" %}">
                Timezone: {{ user.profile.timezone }}&nbsp; <i class="fa fa-edit"></i>
            </a></li>
        </ol>
    </section>

    <!-- section content-header used for symmetry pupose only -->
    <section class="content-header">
        <div class="row">
            <div class="col-md-2">
                <div>&nbsp;</div><!-- just a div to take an empty line -->
                <a href="{% url "manage_users:register_user" %}" class="btn btn-large btn-primary"><i
                        class="fa fa-plus"></i> &nbsp; Add User</a>
            </div>
            <div class="col-md-2">
                <label>Account State</label>
                <select name="account_state" class="form-control" id="account_state">
                    <option value="">All</option>
                    <option value="active">Active</option>
                    <option value="inactive">Inactive</option>
                </select>
            </div>
            <div class="col-md-2">
                <label>Account Type</label>
                <select name="account_type" class="form-control" id="account_type">
                    <option value="">All</option>
                    <option value="wizards">Wizards</option>
                    <option value="judges">Judges</option>
                </select>
            </div>
            <div class="col-md-2">
                <label for="attribute">Filter by</label>
                <select name="attribute" class="form-control" id="attribute">
                    <option value="username">User Name</option>
                    <option value="first_name">First Name</option>
                    <option value="last_name">Last Name</option>
                    <option value="email">Email</option>
                    <option value="role">User Role</option>
                    <option value="contact_no">Contact No</option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="search_term">Search for</label>
                <div class="has-feedback">
                    <input name="search_term" id="search_term" class="form-control" type="text"
                           data-table-id="result-table"
                           data-ajax-url="{% url "manage_users:get_filtered_users" %}" autofocus>
                    <span class="fa fa-search form-control-feedback" aria-hidden="true"></span>
                    <span class="sr-only">(Search)</span>
                </div>
            </div>
        </div>
        <div class="row" id="result-table">
            <div class="col-md-12">
                <div class="x-overflowable">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                        <!--<table class='table table-bordered table-responsive'>-->
                        <tr>
                            <th><a href="#">#</a></th>
                            <th>User Name</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>E-mail</th>
                            <th>User Role</th>
                            <th>Contact No</th>
                            <th>Account state</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in users %}
                            <tr onclick="window.location='{% url "core:user_profile" user.id %}';"
                                style="cursor: pointer;">
                                <td>
                                    <a href="{% url "core:user_profile" user.id %}">
                                        {{ forloop.counter }}
                                    </a>
                                </td>
                                <td>{{ user.username }}</td>
                                <td>{{ user.first_name|default:"---" }}</td>
                                <td>{{ user.last_name|default:"---" }}</td>
                                <td>{{ user.email|default:"---" }}</td>
                                <td>
                                    {% for group in user.groups.all %}
                                        {{ group.name|slice:":-1" }} <br>
                                    {% empty %}
                                        No role
                                    {% endfor %}
                                </td>
                                <td>{{ user.profile.contact_no }}</td>
                                <td>
                                    {% if user.is_active %}
                                        Active
                                    {% else %}
                                        Deactivated
                                    {% endif %}
                                </td>
                                {% comment %}<td align="center">
                                    <a href="{% url "manage_users:edit_user" user.id %}"><i class="fa fa-edit"></i></a>
                                </td>{% endcomment %}

{% comment %}
                                <td align="center">
                                    {% if user.is_active %}
                                        <button href="javascript:void(0)"
                                                class="activate_deactivate_user btn btn-danger" data-id="{{ user.id }}"
                                                data-ajax-url="{% url "manage_users:activate_deactivate_user" %}"
                                                data-user-active="true">
                                            Deactivate
                                        </button>
                                    {% else %}
                                        <button href="javascript:void(0)"
                                                class="activate_deactivate_user btn btn-success" data-id="{{ user.id }}"
                                                data-ajax-url="{% url "manage_users:activate_deactivate_user" %}"
                                                data-user-active="false">
                                            Activate
                                        </button>
                                    {% endif %}
                                </td>
{% endcomment %}
                            </tr>
                        {% empty %}
                            <tr>
                                <td align="center" colspan="9" class="text-bold" style="font-size:2em;">
                                    No Results Found
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            {% include "core/includes/pagination.html" with items=users %}

        </div>
    </section>


{% endblock %}