arv/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^wizards/', include('wizards.urls')),
    url(r'^judges/', include('judges.urls')),
    url(r'^manage_images/', include('manage_images.urls')),
    url(r'^manage_tasks/', include('manage_tasks.urls')),
    url(r'^manage_users/', include('manage_users.urls')),
    url(r'^cue/', include('cue.urls', namespace='cue')),

]

# serve files if we are in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'core'
urlpatterns = [
    # url for login page
    url(r'^(?:accounts/login/)?$', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),

    # user is redirected here when he/she has successfuly logged in i.e "accounts/profile/"
    # then views.role_login will take it from there i.e. handling user types and the like
    url(r'^accounts/profile/$', views.role_login, name='role_login'),

    # url for logout request
    url(r'^accounts/logout/$', views.logout_user, name='logout'),

    # url to edit user's own profile
    url(r'^accounts/self_profile/$', views.self_profile, name="self_profile"),

    # url to confirm email and activate new user
    url(r'^accounts/confirm/activate/(?P<user_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.confirm_and_activate, name="confirm_and_activate"),

    url(r'^dashboard/$', views.admin_dashboard, name="admin_dashboard"),

    # url to display  user detail
    url(r'^user_profile/(?P<user_id>\d+)/$', views.user_profile, name="user_profile"),
]

manage_images/urls.py
from django.conf.urls import url

from manage_images import views as image_views

app_name = 'manage_images'

urlpatterns = [
    # urls that are associated with managing images
    url(r'^add_image/$', image_views.add_image, name='add_image'), # Actually, this one is deprecated and not used
    url(r'^add_images/$', image_views.add_images, name='add_images'),
    url(r'^view_images/$', image_views.view_images, name="view_images"),
    url(r'^get_filtered_images/$', image_views.get_filtered_images, name="get_filtered_images"),
    url(r'^delete_image/$', image_views.delete_image, name="delete_image"),
    url(r'^update_potential_images/(?P<image_id>\d+)/$', image_views.update_potential_images, name="update_potential_images"),
]

manage_tasks/urls.py
from django.conf.urls import url

from manage_tasks import views as task_views

app_name = 'manage_tasks'
urlpatterns = [
    # urls that are associated with managing tasks
    url(r'^create_task/$', task_views.create_task, name="create_task"),
    url(r'^view_tasks/$', task_views.view_tasks, name="view_tasks"),
    url(r'^edit_task/(?P<task_id>\d+)/$', task_views.edit_task, name="edit_task"),
    url(r'^delete_task/$', task_views.delete_task, name="delete_task"),
    url(r'^get_filtered_tasks/$', task_views.get_filtered_tasks, name="get_filtered_tasks"),
    url(r'^get_filtered_wizards/(?P<task_id>\d+)/$', task_views.get_filtered_wizards, name="get_filtered_wizards"),
    url(r'^get_filtered_judges/(?P<task_id>\d+)/$', task_views.get_filtered_judges, name="get_filtered_judges"),
    url(r'^assign_remove_viewers/$', task_views.assign_remove_wizards, name="assign_remove_viewers"),
    url(r'^assign_remove_judges/$', task_views.assign_remove_judges, name="assign_remove_judges"),
 
]

manage_users/urls.py
from django.conf.urls import url

from . import views

app_name = 'manage_users'
urlpatterns = [
    # urls that are associated with managing users
    url(r'^view_users/$', views.view_users, name="view_users"),
    url(r'^register_user/$', views.register_user, name='register_user'),

    # deprecated view url
    # url(r'^edit_user/(?P<user_id>\d+)/$', views.edit_user, name="edit_user"),

    url(r'^get_filtered_users/$', views.get_filtered_users, name="get_filtered_users"),

    url(r'^activate_deactivate_user/$', views.activate_deactivate_user, name="activate_deactivate_user"),
]

core/models.py
from django.db import models
from django.conf import settings

from django.utils import timezone

import uuid
import os
import pytz

"""
all timezones from pytz library as pairs
"""
all_timezones = zip(pytz.all_timezones, pytz.all_timezones)


def user_profile_picture_path(instance, filename):
    """
    Generate a path for a profile picture storage with unique filename

    Args:
        instance: don't know it
        filename: filename of uploaded file

    Returns:
        A path including filename relative to the media folder that will be used to store the uploaded file
    """

    # get the extension of the file
    ext = filename.split('.')[-1]

    # every user's profile picture will be stored in his/her own folder that is named using user's id
    folder_name = "user_{0}".format(instance.user.id)
    filename = "{0}.{1}".format(uuid.uuid4(), ext)

    return os.path.join(settings.PROFILE_PICTURE_FOLDER, folder_name, filename)


class Profile(models.Model):
    """
    Profile model that consists additional information for a specific user
    """

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    contact_no = models.CharField(max_length=15, blank=True)
    picture = models.ImageField(upload_to=user_profile_picture_path, default="anonymous.png", unique=False)
    timezone = models.CharField(max_length=255, choices=all_timezones, default=timezone.get_current_timezone_name())

    # number of tasks finished by the user
    finished_tasks = models.PositiveIntegerField(default=0)
    # number of tasks expired
    expired_tasks = models.PositiveIntegerField(default=0)
    # number of tasks that are successfully predicted by the user
    success_tasks = models.PositiveIntegerField(default=0)
    # number of tasks that are currently assigned and being done by the user
    active_tasks = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "Profile of {}".format(self.user.username)

core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms import ModelForm
from django.contrib.auth.models import User

from core.models import Profile

# possible groups in the system with their friendly name
groups = [
    ("wizards", "Wizard"),
    ("judges", "Judge"),
]


class ImageForm(forms.Form):
    """
    A form to only check if uploaded image is valid
    """

    image = forms.ImageField()


class EditUserForm(ModelForm):
    """
    A form to edit user information excluding profile information
    """

    def __init__(self, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            if 'required' in field.error_messages:
                field.error_messages['required'] = '{0} is required'.format(key)

    role = forms.ChoiceField(choices=groups, required=True)
    change_password = forms.CharField(max_length=100, required=False)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class ProfileForm(ModelForm):
    """
    A form to edit profile information of a user
    """

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            if 'required' in field.error_messages:
                field.error_messages['required'] = '{0} is required'.format(key)

    class Meta:
        model = Profile
        fields = ['contact_no', 'picture', 'timezone']


class TimezoneForm(ModelForm):
    """
    A form to change a timezone of a user
    """

    def __init__(self, *args, **kwargs):
        super(TimezoneForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            if 'required' in field.error_messages:
                field.error_messages['required'] = '{0} is required'.format(key)

    class Meta:
        model = Profile
        fields = ['timezone']


class UserForm(ModelForm):
    """
    A form for adding new user
    """

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            if 'required' in field.error_messages:
                field.error_messages['required'] = '{0} is required'.format(key)

    role = forms.ChoiceField(choices=groups, required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_email(self):
        email = self.cleaned_data['email']

        if not email:
            raise forms.ValidationError("An email is required")

        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("A user with the same email already exists.")

        return email

core/views.py
from django.contrib.auth import logout, get_user_model, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from core.tokens import account_activation_token
from core.utils import is_admin, edit_user_logic, get_user_profile, get_finished_tasks, get_expired_tasks, \
    get_unfinished_tasks, get_success_tasks
from judges.views import is_judge
from manage_images.models import Image
from manage_tasks.models import Task
from wizards.views import is_wizard


@login_required
def role_login(request):
    """
    # login user based on the role of user
    """

    if is_wizard(request.user):
        return redirect(reverse('wizards:unfinished_tasks'))
    elif is_judge(request.user):
        return redirect(reverse('judges:unfinished_tasks'))
    else:
        return redirect(reverse("core:login"))


def logout_user(request):
    """
    # log a user out
    """

    logout(request)
    return redirect(reverse("core:login"))


@login_required
def self_profile(request):
    """
    A view to see details of user's own profile and edit his/her details

    Args:
        request: the http request

    Returns:
        An http redirect to itself if editing user failed or
        an html with appropriate messages if necessary
    """

    kwargs = {
        'is_wizard': is_wizard(request.user),
        'is_judge': is_judge(request.user)
    }

    finished_tasks = get_finished_tasks(request.user, **kwargs)
    expired_tasks = get_expired_tasks(request.user, **kwargs)
    unfinished_tasks = get_unfinished_tasks(request.user, **kwargs)
    success_tasks, unsuccess_tasks, total_tasks = get_success_tasks(request.user, **kwargs)

    success_tasks_percent = get_percent(success_tasks, total_tasks)
    if kwargs['is_wizard']:
        finished_tasks_percent = get_percent(finished_tasks, request.user.wizard_tasks.count())
        expired_tasks_percent = get_percent(expired_tasks, request.user.wizard_tasks.count())
        # active_tasks_percent = get_percent(unfinished_tasks, Task.objects.filter(wizardassignment__state__lte=Task.UNFINISHED).count())
    elif kwargs['is_judge']:
        finished_tasks_percent = get_percent(finished_tasks, request.user.judge_tasks.count())
        expired_tasks_percent = get_percent(expired_tasks, request.user.judge_tasks.count())
        # active_tasks_percent = get_percent(unfinished_tasks, Task.objects.filter(judgeassignment__state__lte=Task.UNFINISHED).count())
    else:
        return HttpResponseBadRequest()

    context = {
        "finished_tasks": finished_tasks,
        "finished_tasks_percent": finished_tasks_percent,
        "success_tasks": success_tasks,
        "success_tasks_percent": success_tasks_percent,
        "expired_tasks": expired_tasks,
        "expired_tasks_percent": expired_tasks_percent,
        "unfinished_tasks": unfinished_tasks,
        # "active_tasks_percent": active_tasks_percent,
    }

    # process logic for editing user and profile
    response = edit_user_logic(request, request.user, role_change=False)

    # if the response is http redirect, redirect
    # else the response is context variables for template
    if isinstance(response, HttpResponseRedirect):
        return response
    else:
        context.update(response)

    return render(request, "core/self_profile.html", context)




def confirm_and_activate(request, new_user_id, token):
    """
    Confirm a user email is right and activate his/her account

    Redirects to the homepage of the user
    """

    try:
        # user_id = force_text(urlsafe_base64_decode(user_id_b64))
        user_id = int(new_user_id)
        user = get_user_model().objects.get(pk=user_id)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        login(request, user)

        return redirect("core:role_login")


@user_passes_test(is_admin)
def admin_dashboard(request):
    """
    Admin dashboard view for admin
    """

    tasks_count = Task.objects.count()
    images_count = Image.objects.count()
    users_count = get_user_model().objects.exclude(is_superuser=True).count()
    inactive_users_count = get_user_model().objects.filter(is_active=False).count()

    context = {
        "tasks_count": tasks_count,
        "images_count": images_count,
        "users_count": users_count,
        "inactive_users_count": inactive_users_count,
    }

    return render(request, "core/dashboard.html", context)


@user_passes_test(is_admin)
def user_profile(request, user_id):
    """
    A view to see details of a specific user and edit his/her details

    Args:
        request: the http request
        user_id: the current user to be edited

    Returns:
        An http redirect to itself if editing user failed or
        an html with appropriate messages if necessary
    """

    selected_user = get_object_or_404(get_user_model(), pk=user_id)
    kwargs = {
        'is_wizard': is_wizard(request.user),
        'is_judge': is_judge(request.user)
    }

    finished_tasks = get_finished_tasks(request.user, **kwargs)
    expired_tasks = get_expired_tasks(request.user, **kwargs)
    unfinished_tasks = get_unfinished_tasks(request.user, **kwargs)
    success_tasks, unsuccess_tasks, total_tasks = get_success_tasks(request.user, **kwargs)

    success_tasks_percent = get_percent(success_tasks, total_tasks)
    if kwargs['is_wizard']:
        finished_tasks_percent = get_percent(finished_tasks, request.user.wizard_tasks.count())
        expired_tasks_percent = get_percent(expired_tasks, request.user.wizard_tasks.count())
        # active_tasks_percent = get_percent(unfinished_tasks, Task.objects.filter(wizardassignment__state__lte=Task.UNFINISHED).count())
    elif kwargs['is_judge']:
        finished_tasks_percent = get_percent(finished_tasks, request.user.judge_tasks.count())
        expired_tasks_percent = get_percent(expired_tasks, request.user.judge_tasks.count())
        # active_tasks_percent = get_percent(unfinished_tasks, Task.objects.filter(judgeassignment__state__lte=Task.UNFINISHED).count())
    else:
        return HttpResponseBadRequest()

    context = {
        "selected_user": selected_user,
        "finished_tasks": finished_tasks,
        "finished_tasks_percent": finished_tasks_percent,
        "success_tasks": success_tasks,
        "success_tasks_percent": success_tasks_percent,
        "expired_tasks": expired_tasks,
        "expired_tasks_percent": expired_tasks_percent,
        "unfinished_tasks": unfinished_tasks,
        # "active_tasks_percent": active_tasks_percent,
    }

    # process logic for editing user and profile
    response = edit_user_logic(request, selected_user)

    # if the response is http redirect, redirect
    # else the response is context variables for template
    if isinstance(response, HttpResponseRedirect):
        return response
    else:
        context.update(response)

    return render(request, "core/user_profile.html", context)


def get_percent(numerator, denominator):
    """
    Get percentage based on numerator and denominator
    and evaluate to 0 if denominator is 0
    """

    if denominator == 0:
        return 0
    else:
        return numerator/denominator * 100

core/templates/core/dashboard.html
{% extends "judges/extends/base.html" %}

{% block title %} ARV | Dashboard {% endblock %}
{% block main_content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="margin-left: -10px;margin-top: 20px">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Dashboard
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <div class="row">
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3>{{ tasks_count }}</h3>

              <p>Tasks</p>
            </div>
            <div class="icon">
              <i class="ion ion-clipboard"></i>
            </div>
            <a href="{% url "manage_tasks:view_tasks" %}"  class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3>{{ images_count }}</h3>

              <p>Images</p>
            </div>
            <div class="icon">
              <i class="ion ion-image"></i>
            </div>
            <a href="{% url "manage_images:view_images" %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3>{{ users_count }}</h3>

              <p>Users</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href="{% url "manage_users:view_users" %}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3>{{ inactive_users_count }}</h3>

              <p>Inactive Users</p>
            </div>
            <div class="icon">
              <i class="ion ion-pie-graph"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
      </div>
      <!-- /.row -->


    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock main_content %}

core/templates/core/login.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ARV | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% load static %}
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static "dist/css/AdminLTE.min.css" %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static "plugins/iCheck/square/blue.css" %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="#"><b> ARV </b> Experiment</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        {% if  form.errors %}
            <div class="alert alert-danger">
                <p class="text-center">
                    <i class="glyphicon glyphicon-warning-sign"></i>
                    Your username and password did not match! <br/>
                    Please, try again.
                </p>
            </div>
        {% endif %}

        <form role="form" action="" method="post">
            {% csrf_token %}
            <div class="form-group has-feedback">
                <input type="text" name="username" placeholder="Username" id="username" class="form-control"
                       required>
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" name="password" class="form-control" placeholder="Password" required>
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <!--<div class="checkbox icheck">
                      <label>
                        <input type="checkbox"> Remember Me
                      </label>
                    </div>-->
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" name="btn-login" class="btn btn-primary btn-block btn-flat">Sign In</button>
                </div>
                <!-- /.col -->
            </div>
        </form>

        <!--<div class="social-auth-links text-center">
          <p>- OR -</p>
          <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
            Facebook</a>
          <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
            Google+</a>
        </div>
        <!-- /.social-auth-links -->

        <a href="#">I forgot my password </a><code>Not yet implemented! </code> <br>
        <a href="register.html" class="text-center">Register a new membership</a><code>Not yet implemented!</code>

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 2.2.3 -->
<script src={% static "plugins/jQuery/jquery-2.2.3.min.js" %}></script>
<!-- Bootstrap 3.3.6 -->
<script src={% static "bootstrap/js/bootstrap.min.js" %}></script>
<!-- iCheck -->
<script src={% static "plugins/iCheck/icheck.min.js" %}></script>
<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' // optional
        });
    });
</script>
</body>
</html>