arv/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^wizards/', include('wizards.urls')),
    url(r'^judges/', include('judges.urls')),
    url(r'^manage_images/', include('manage_images.urls')),
    url(r'^manage_tasks/', include('manage_tasks.urls')),
    url(r'^manage_users/', include('manage_users.urls')),
    url(r'^cue/', include('cue.urls', namespace='cue')),

]

# serve files if we are in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'core'
urlpatterns = [
    # url for login page
    url(r'^(?:accounts/login/)?$', auth_views.LoginView.as_view(template_name='core/login.html'), name='login'),

    # user is redirected here when he/she has successfuly logged in i.e "accounts/profile/"
    # then views.role_login will take it from there i.e. handling user types and the like
    url(r'^accounts/profile/$', views.role_login, name='role_login'),

    # url for logout request
    url(r'^accounts/logout/$', views.logout_user, name='logout'),

    # url to edit user's own profile
    url(r'^accounts/self_profile/$', views.self_profile, name="self_profile"),

    # url to confirm email and activate new user
    url(r'^accounts/confirm/activate/(?P<user_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.confirm_and_activate, name="confirm_and_activate"),

    url(r'^dashboard/$', views.admin_dashboard, name="admin_dashboard"),

    # url to display  user detail
    url(r'^user_profile/(?P<user_id>\d+)/$', views.user_profile, name="user_profile"),
]

manage_images/urls.py
from django.conf.urls import url

from manage_images import views as image_views

app_name = 'manage_images'

urlpatterns = [
    # urls that are associated with managing images
    url(r'^add_image/$', image_views.add_image, name='add_image'), # Actually, this one is deprecated and not used
    url(r'^add_images/$', image_views.add_images, name='add_images'),
    url(r'^view_images/$', image_views.view_images, name="view_images"),
    url(r'^get_filtered_images/$', image_views.get_filtered_images, name="get_filtered_images"),
    url(r'^delete_image/$', image_views.delete_image, name="delete_image"),
    url(r'^update_potential_images/(?P<image_id>\d+)/$', image_views.update_potential_images, name="update_potential_images"),
]

manage_images/models.py
from django.db import models

from arv import settings


class Image(models.Model):
    """
    Model Image to represent image that will be used to create task
    """

    image = models.ImageField(unique=True, upload_to=settings.TASK_IMAGES_FOLDER)
    caption = models.CharField(max_length=100, blank=True)
    description = models.CharField(max_length=150, blank=True)
    upload_date = models.DateTimeField(auto_now_add=True)

    potentials = models.ManyToManyField("self")

    def __str__(self):
        return self.caption or self.description or super().__str__()

    class Meta:
        ordering = ["id"]


# Model to persist tha recent last used images in order to avoid repeating of images
class RecentImage(models.Model):
    image = models.OneToOneField(Image, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.image)

manage_images/forms.py
from django.forms import ModelForm, forms

from .models import Image


class ImageUploadForm(ModelForm):
    """
    A model form to upload an image which will be used with task
    """

    def __init__(self, *args, **kwargs):
        super(ImageUploadForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            if 'required' in field.error_messages:
                field.error_messages['required'] = '{0} is required'.format(key)

    def clean_image(self):
        """
        Checks the validity of the image name
        i.e. An image name should be a unique number
        """
        image = self.cleaned_data["image"]


        dot_index = image.name.rfind(".")
        if dot_index == -1:
            raise forms.ValidationError(
                "The name of the image file should include extension", code="invalid_number"
            )

        image_name = image.name[:dot_index]
        try:
            image_id = int(image_name)
            if Image.objects.filter(id__exact=image_id).exists():
                raise forms.ValidationError(
                    "The id {} is already used by another image".format(image_id),
                    code="invalid_id"
                )
            else:
                return image
        except ValueError:
            raise forms.ValidationError(
                "The name of the image file must be only a number", code="invalid_id"
            )

    def save(self, force_insert=False, force_update=False, commit=True):
        """
        Assumes:
            The filename of the image is a valid number

        Saves the model using the filename as number field for the model
        """

        image = super(ImageUploadForm, self).save(commit=False)

        # assume the name of the image is clean
        # i.e. the name of the image is an acceptable integer
        dot_index = image.image.name.rfind(".")
        image.id = int(image.image.name[:dot_index])

        if commit:
            image.save()

        return image


    class Meta:
        model = Image
        fields = ('image', 'caption', 'description',)


class PotentialImageUpdateForm(ModelForm):
    """
    A model form to update an image's potential images which will be used for task creation
    """

    def __init__(self, *args, **kwargs):
        super(PotentialImageUpdateForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            if 'required' in field.error_messages:
                field.error_messages['required'] = '{0} is required'.format(key)


    class Meta:
        model = Image
        fields = ('potentials',)

    def save(self, force_insert=False, force_update=False, commit=True):
        """
        Add or remove potential images accordingly, ignore adding itself as potential
        """

        image = super(PotentialImageUpdateForm, self).save(commit=False)

        image.potentials.clear()
        for potential in self.cleaned_data['potentials'].all():
            if image.id != potential.id:
                image.potentials.add(potential)

        if commit:
            image.save()

        return image

manage_images/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.template import loader

from manage_images.forms import ImageUploadForm, PotentialImageUpdateForm
from manage_images.models import Image

from core.utils import get_status, get_paginated_items, get_pages, ajax_required, is_admin


@ajax_required
@user_passes_test(is_admin)
def add_images(request):
    """
    A view to add/upload multiple images asynchronously i.e. the AJAX way
    """

    if request.method == "POST":
        image_form = ImageUploadForm(request.POST, request.FILES)

        data = {"name": request.FILES["image"].name}

        if image_form.is_valid():
            image_form.save()

            data['uploaded'] = True

        else:
            data['uploaded'] = False

            data['errors'] = image_form.errors

        return JsonResponse(data)


# N.B This view is deprecated and not used
@user_passes_test(is_admin)
def add_image(request):
    """
    A view to add/upload new single task image
    """

    if request.method == "POST":
        image_form = ImageUploadForm(request.POST, request.FILES)

        if image_form.is_valid():
            image_form.save()

            # save the success info if the uploading process was successful
            request.session['uploaded'] = True
        else:
            # save the failure info if the uploading process was unsuccessful
            request.session['not_uploaded'] = True

            # save the errors that could arise from form submission
            request.session['image_form_errors'] = image_form.errors

        return redirect(request.path)

    else:
        image_form = ImageUploadForm()

    # check if there was successful upload of image and invalidate it
    success = get_status(request, 'uploaded', False)
    # check if there was unsuccessful upload of image and invalidate it
    failure = get_status(request, 'not_uploaded', False)
    # get errors if there are any and invalidate them
    image_form_errors = get_status(request, 'image_form_errors', {})

    # context variables for template
    context = {
        "image_form": image_form,
        "success": success,
        "failure": failure,
        "image_form_errors": image_form_errors,
    }

    return render(request, "manage_images/add_images.html", context)


@user_passes_test(is_admin)
def view_images(request):
    """
    A view to show all task images
    """

    images_list = Image.objects.all()

    # get images on current page
    images = get_paginated_items(request, images_list)

    # get page number range
    pages, many_pages = get_pages(images)

    # context variables for template
    context = {
        'images': images,
        'pages': pages,
        'many_pages': many_pages,
        'all_images': images_list,
    }

    return render(request, "manage_images/view_images.html", context)


@ajax_required
@user_passes_test(is_admin)
def get_filtered_images(request):
    """
    Return a table of images filtered by submitted criteria
    """

    # get the user attribute to be filtered
    attribute = request.GET.get("attribute")
    # get the search term
    search_term = request.GET.get("search_term").strip()

    if len(search_term) == 0:
        # we don't need filtering criteria
        kwargs = {}

    elif attribute == "id":
        try:
            int(search_term)

            # construct keyword args for field look up if number is integer
            kwargs = {
                "{0}__{1}".format(attribute, "exact"): search_term,
            }
        except ValueError:
            # construct keyword args for field look up if number is not integer
            kwargs = {
                "{0}__{1}".format(attribute, "exact"): 0,
            }

    else:
        # construct keyword args for field look up
        kwargs = {
            "{0}__{1}".format(attribute, "icontains"): search_term,
        }

    images_list = Image.objects.filter(**kwargs)

    # get images on current page
    images = get_paginated_items(request, images_list)

    # get page number range
    pages, many_pages = get_pages(images)

    context = {
        "images": images,
        "pages": pages,
        "many_pages": many_pages,
    }

    return render(request, "manage_images/ajax_responses/filtered_images_table.html", context)


@ajax_required
@user_passes_test(is_admin)
def delete_image(request):
    """
    Deletes a task image (N.B. Not used feature)

    Actually, an image must be checked if it is in active use for a task or tasks
    which will definitely lead to abnormal behavior and useless scenario, consequently
    this feature is dropped for now because no check up is made.
    """

    image_id = int(request.POST['item_id'])
    image = get_object_or_404(Image, pk=image_id)

    # image.delete()

    return HttpResponse("You can not delete any image.Any image may be in active use.")


@user_passes_test(is_admin)
def update_potential_images(request, image_id):
    """
    Updates potential images for a specific image

    Redirects to view_images page
    """

    image = get_object_or_404(Image, pk=image_id)
    potential_images_form = PotentialImageUpdateForm(request.POST, instance=image)

    if potential_images_form.is_valid():
        potential_images_form.save()

    return redirect("manage_images:view_images")

manage_images/templates/manage_images/add_image.html
{% extends "judges/extends/base.html" %}

{% block title %} ARV | Add Image {% endblock %}

{% block heading %} Upload Image {% endblock %}

{% block main_content %}
    <section class="content-header">
        <h1 class="text-bold underlined-heading">
            Add new image
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url "core:self_profile" %}">
                Timezone: {{ user.profile.timezone }}&nbsp; <i class="fa fa-edit"></i>
            </a></li>
        </ol>
    </section>

    <!-- section content-header used for symmetry pupose only -->
    <section class="content-header">
        <div class="row">
            <div class="col-md-12">

                {% if image_form_errors %}
                    {% for field, errors in image_form_errors.items %}
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4>
                                <i class="icon fa fa-warning"></i>
                                Upload failed!
                            </h4>
                            {{ errors.0|escape }} !
                        </div>
                    {% endfor %}
                {% else %}
                    {% if success %}
                        <div class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4>
                                <i class="icon fa fa-check"></i>
                                Alert!
                            </h4>
                            Image is successfully uploaded.
                        </div>
                    {% endif %}
                    {% if failure %}
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <<h4>
                            <i class="icon fa fa-warning"></i>
                            Alert!
                        </h4>
                            Error while uploading image. Please, try again !
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">

                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label">Choose Image </label>
                        <input class="input-group" type="file" multiple name="image" id="image_to_upload" accept="image/*"/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Caption </label>
                        <input class="form-control" type="text" name="caption" placeholder="Enter Image Caption"
                               value=""/>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Description </label>
                        <textarea class="form-control" type="text" name="description" placeholder="Your Description"
                               value=""> </textarea>
                    </div>
                    <!--div class="form-group">
                        <label class="control-label">Tags
                            <small>( Write multiple tags separated by comma )</small>
                        </label>
                        <textarea class="form-control" name="tags" placeholder="" value="">

                         </textarea>
                    </div-->

                    <!--<button type="submit" class="btn btn-info "> Save </button>
                  <button type="submit" class="btn btn-default"> Cancel </button>-->
                    <button type="submit" class="btn btn-primary" name="btn-save">
                        <span class="fa fa-upload"></span>&nbsp; Upload Image
                    </button>

                </form>
                <!-- /.form-group -->
            </div>
            <!-- /.col -->
            <div class="col-md-6">
                <label>Image Preview</label>
                <p id="image_status">No Image Chosen</p>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

{% endblock %}

manage_images/templates/manage_images/add_images.html
{% extends "judges/extends/base.html" %}

{% block title %} ARV | Add Images {% endblock %}

{% block heading %} Upload Images {% endblock %}

{% block main_content %}
    <section class="content-header">
        <h1 class="text-bold underlined-heading">
            Add new images
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url "core:self_profile" %}">
                Timezone: {{ user.profile.timezone }}&nbsp; <i class="fa fa-edit"></i>
            </a></li>
        </ol>
    </section>

    <!-- section content-header used for symmetry pupose only -->
    <section class="content-header">

        <div class="row" style="margin-bottom: 2em;">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label">Choose Images </label>
                    <input class="input-group" type="file" multiple name="image" id="fileupload_input" accept="image/*"
                           style="display: none;"
                           data-url="{% url 'manage_images:add_images' %}"/>
                </div>

                <button class="btn btn-primary js-upload-photos">
                    <span class="fa fa-upload"></span>&nbsp; Upload Images
                </button>


            </div>
            <!-- /.col -->

        </div>
        <!-- /.row -->

        <div class="row">

            <!-- A div to show status messages about uploading images -->
            <div class="col-md-12" id="feedback_div">

            </div>
        </div>
    </section>

    <!-- A progress bar to indicate uploading status -->
    <div class="modal" id="modal-progress">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" style="text-align: center;">
                    <h4> Uploading ... </h4>
                </div>

                <div class="modal-body">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped active" style="width: 0%"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

manage_images/templates/manage_images/view_images.html
{% extends "judges/extends/base.html" %}

{% block title %} ARV | View Images {% endblock %}

{% block main_content %}
    <section class="content-header">
        <h1 class="text-bold underlined-heading">
            All Images
        </h1>
        <ol class="breadcrumb">
            <li><a href="{% url "core:self_profile" %}">
                Timezone: {{ user.profile.timezone }}&nbsp; <i class="fa fa-edit"></i>
            </a></li>
        </ol>
    </section>

    <!-- section content-header used for symmetry pupose only -->
    <section class="content-header">
        <div class="row">
            <div class="col-md-6">
                <div>&nbsp;</div><!-- just a div to take an empty line -->
                <a href="{% url "manage_images:add_image" %}" class="btn btn-large btn-primary"><i
                        class="fa fa-plus"></i> &nbsp; Add Image </a>
            </div>
            <div class="col-md-2">
                <label for="attribute">Filter by</label>
                <select name="attribute" class="form-control" id="attribute">
                    <option value="id">ID</option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="search_term">Search for</label>
                <div class="has-feedback">
                    <input name="search_term" id="search_term" class="form-control" type="text"
                           data-table-id="result-table"
                           data-ajax-url="{% url "manage_images:get_filtered_images" %}">
                    <span class="fa fa-search form-control-feedback" aria-hidden="true"></span>
                    <span class="sr-only">(Search)</span>
                </div>
            </div>
        </div>

        <div class="row" id="result-table">
            <div class="col-md-12">
                <div class="x-overflowable">
                    <table class="table table-striped table-bordered table-hover" id="images-table">
                        <thead>
                        <!--<table class='table table-bordered table-responsive'>-->
                        <tr>
                            <th>ID</th>
                            <th>Image</th>
                            <th>Potential pair</th>
                            {% comment %} <th>Caption</th>
                            <th>Description</th>{% endcomment %}

                        </tr>
                        </thead>

                        {% load thumbnail %}

                        <tbody>
                        {% for image in images %}
                            <tr>
                                <td>{{ image.id }}</td>
                                <td>
                                    {% thumbnail image.image "200" as im %}
                                        <img src="{{ im.url }}" alt="{{ image.description|default:image.id }}"/>
                                    {% endthumbnail %}
                                </td>
                                <td>
                                    <form action="{% url "manage_images:update_potential_images" image.id %}" method="POST">
                                        {% csrf_token %}

                                        <select class="js-example-basic-multiple" name="potentials" title="potentials"
                                                style="width: 196px;" id="{{ image.id }}" multiple="multiple">
                                            {% for potential in image.potentials.values %}
                                                <option value="{{ potential.id }}" selected="selected">
                                                    {{ potential.id }}
                                                </option>
                                            {% endfor %}
                                            {% for image_obj in all_images %}
                                                {% if not image_obj in image.potentials.all %}
                                                    <option value="{{ image_obj.id }}">
                                                        {{ image_obj.id }}
                                                    </option>
                                                {% endif %}
                                            {% endfor %}
                                        </select>
                                        <input type="submit" value="Update" class="btn btn-success">
                                    </form>
                                </td>
                                {% comment %}<td>{{ image.caption|default:"---" }}</td>
                                <td>{{ image.description|default:"---" }}</td>{% endcomment %}
                                {% comment %}<td align="center">
                                    <a href="#"><i class="fa fa-edit"></i></a>
                                </td>{% endcomment %}

                            </tr>
                        {% empty %}
                            <tr>
                                <td align="center" colspan="9" class="text-bold" style="font-size:2em;">
                                    No Results Found
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>

            {% include "core/includes/pagination.html" with items=images %}

        </div>
    </section>
{% endblock main_content %}